using System.Collections.Generic;

namespace Jx.Toolbox.Utils
{
    public class MimeUtil
    {
        /// <summary>
        /// 默认的Mime
        /// </summary>
        public static string DefaultMime = "application/octet-stream";

        /// <summary>
        /// 根据扩展名获取Mime
        /// </summary>
        /// <param name="extension"></param>
        /// <returns></returns>
        public static string GetMimeFromExtension(string extension)
        {
            if (!extension.StartsWith("."))
            {
                extension = "." + extension;
            }

            return MimeItems.Find(x => x.Extension == extension)?.Mime ?? DefaultMime;
        }

        /// <summary>
        /// 根据扩展名获取大类
        /// </summary>
        /// <param name="extension"></param>
        /// <returns></returns>
        public static string GetTypeFormExtension(string extension)
        {
            var mime = GetMimeFromExtension(extension);
            return mime.Split('/')[0];
        }

        /// <summary>
        /// 根据Mime获取扩展名，如果未找到，返回null
        /// </summary>
        /// <param name="mime"></param>
        /// <returns></returns>
        public static string GetExtensionFromMime(string mime)
        {
            return MimeItems.Find(x => x.Mime == mime)?.Extension;
        }

        /// <summary>
        /// 默认Mime列表
        /// </summary>
        public static List<MimeItem> MimeItems = new List<MimeItem>()
        {
            new MimeItem(".323", "text/h323"),
            new MimeItem(".3gp", "video/3gpp"),
            new MimeItem(".aab", "application/x-authoware-bin"),
            new MimeItem(".aam", "application/x-authoware-map"),
            new MimeItem(".aas", "application/x-authoware-seg"),
            new MimeItem(".acx", "application/internet-property-stream"),
            new MimeItem(".ai", "application/postscript"),
            new MimeItem(".aif", "audio/x-aiff"),
            new MimeItem(".aifc", "audio/x-aiff"),
            new MimeItem(".aiff", "audio/x-aiff"),
            new MimeItem(".als", "audio/X-Alpha5"),
            new MimeItem(".amc", "application/x-mpeg"),
            new MimeItem(".ani", "application/octet-stream"),
            new MimeItem(".apk", "application/vnd.android.package-archive"),
            new MimeItem(".asc", "text/plain"),
            new MimeItem(".asd", "application/astound"),
            new MimeItem(".asf", "video/x-ms-asf"),
            new MimeItem(".asn", "application/astound"),
            new MimeItem(".asp", "application/x-asap"),
            new MimeItem(".asr", "video/x-ms-asf"),
            new MimeItem(".asx", "video/x-ms-asf"),
            new MimeItem(".au", "audio/basic"),
            new MimeItem(".avb", "application/octet-stream"),
            new MimeItem(".avi", "video/x-msvideo"),
            new MimeItem(".awb", "audio/amr-wb"),
            new MimeItem(".axs", "application/olescript"),
            new MimeItem(".bas", "text/plain"),
            new MimeItem(".bcpio", "application/x-bcpio"),
            new MimeItem(".bin ", "application/octet-stream"),
            new MimeItem(".bld", "application/bld"),
            new MimeItem(".bld2", "application/bld2"),
            new MimeItem(".bmp", "image/bmp"),
            new MimeItem(".bpk", "application/octet-stream"),
            new MimeItem(".bz2", "application/x-bzip2"),
            new MimeItem(".c", "text/plain"),
            new MimeItem(".cal", "image/x-cals"),
            new MimeItem(".cat", "application/vnd.ms-pkiseccat"),
            new MimeItem(".ccn", "application/x-cnc"),
            new MimeItem(".cco", "application/x-cocoa"),
            new MimeItem(".cdf", "application/x-cdf"),
            new MimeItem(".cer", "application/x-x509-ca-cert"),
            new MimeItem(".cgi", "magnus-internal/cgi"),
            new MimeItem(".chat", "application/x-chat"),
            new MimeItem(".class", "application/octet-stream"),
            new MimeItem(".clp", "application/x-msclip"),
            new MimeItem(".cmx", "image/x-cmx"),
            new MimeItem(".co", "application/x-cult3d-object"),
            new MimeItem(".cod", "image/cis-cod"),
            new MimeItem(".conf", "text/plain"),
            new MimeItem(".cpio", "application/x-cpio"),
            new MimeItem(".cpp", "text/plain"),
            new MimeItem(".cpt", "application/mac-compactpro"),
            new MimeItem(".crd", "application/x-mscardfile"),
            new MimeItem(".crl", "application/pkix-crl"),
            new MimeItem(".crt", "application/x-x509-ca-cert"),
            new MimeItem(".csh", "application/x-csh"),
            new MimeItem(".csm", "chemical/x-csml"),
            new MimeItem(".csml", "chemical/x-csml"),
            new MimeItem(".css", "text/css"),
            new MimeItem(".cur", "application/octet-stream"),
            new MimeItem(".dcm", "x-lml/x-evm"),
            new MimeItem(".dcr", "application/x-director"),
            new MimeItem(".dcx", "image/x-dcx"),
            new MimeItem(".der", "application/x-x509-ca-cert"),
            new MimeItem(".dhtml", "text/html"),
            new MimeItem(".dir", "application/x-director"),
            new MimeItem(".dll", "application/x-msdownload"),
            new MimeItem(".dmg", "application/octet-stream"),
            new MimeItem(".dms", "application/octet-stream"),
            new MimeItem(".doc", "application/msword"),
            new MimeItem(".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"),
            new MimeItem(".dot", "application/msword"),
            new MimeItem(".dvi", "application/x-dvi"),
            new MimeItem(".dwf", "drawing/x-dwf"),
            new MimeItem(".dwg", "application/x-autocad"),
            new MimeItem(".dxf", "application/x-autocad"),
            new MimeItem(".dxr", "application/x-director"),
            new MimeItem(".ebk", "application/x-expandedbook"),
            new MimeItem(".emb", "chemical/x-embl-dl-nucleotide"),
            new MimeItem(".embl", "chemical/x-embl-dl-nucleotide"),
            new MimeItem(".eps", "application/postscript"),
            new MimeItem(".epub", "application/epub+zip"),
            new MimeItem(".eri", "image/x-eri"),
            new MimeItem(".es", "audio/echospeech"),
            new MimeItem(".esl", "audio/echospeech"),
            new MimeItem(".etc", "application/x-earthtime"),
            new MimeItem(".etx", "text/x-setext"),
            new MimeItem(".evm", "x-lml/x-evm"),
            new MimeItem(".evy", "application/envoy"),
            new MimeItem(".exe", "application/octet-stream"),
            new MimeItem(".fh4", "image/x-freehand"),
            new MimeItem(".fh5", "image/x-freehand"),
            new MimeItem(".fhc", "image/x-freehand"),
            new MimeItem(".fif", "application/fractals"),
            new MimeItem(".flr", "x-world/x-vrml"),
            new MimeItem(".flv", "flv-application/octet-stream"),
            new MimeItem(".fm", "application/x-maker"),
            new MimeItem(".fpx", "image/x-fpx"),
            new MimeItem(".fvi", "video/isivideo"),
            new MimeItem(".gau", "chemical/x-gaussian-input"),
            new MimeItem(".gca", "application/x-gca-compressed"),
            new MimeItem(".gdb", "x-lml/x-gdb"),
            new MimeItem(".gif", "image/gif"),
            new MimeItem(".gps", "application/x-gps"),
            new MimeItem(".gtar", "application/x-gtar"),
            new MimeItem(".gz", "application/x-gzip"),
            new MimeItem(".h", "text/plain"),
            new MimeItem(".hdf", "application/x-hdf"),
            new MimeItem(".hdm", "text/x-hdml"),
            new MimeItem(".hdml", "text/x-hdml"),
            new MimeItem(".hlp", "application/winhlp"),
            new MimeItem(".hqx", "application/mac-binhex40"),
            new MimeItem(".hta", "application/hta"),
            new MimeItem(".htc", "text/x-component"),
            new MimeItem(".htm", "text/html"),
            new MimeItem(".html", "text/html"),
            new MimeItem(".hts", "text/html"),
            new MimeItem(".htt", "text/webviewhtml"),
            new MimeItem(".ice", "x-conference/x-cooltalk"),
            new MimeItem(".ico", "image/x-icon"),
            new MimeItem(".ief", "image/ief"),
            new MimeItem(".ifm", "image/gif"),
            new MimeItem(".ifs", "image/ifs"),
            new MimeItem(".iii", "application/x-iphone"),
            new MimeItem(".imy", "audio/melody"),
            new MimeItem(".ins", "application/x-internet-signup"),
            new MimeItem(".ips", "application/x-ipscript"),
            new MimeItem(".ipx", "application/x-ipix"),
            new MimeItem(".isp", "application/x-internet-signup"),
            new MimeItem(".it", "audio/x-mod"),
            new MimeItem(".itz", "audio/x-mod"),
            new MimeItem(".ivr", "i-world/i-vrml"),
            new MimeItem(".j2k", "image/j2k"),
            new MimeItem(".jad", "text/vnd.sun.j2me.app-descriptor"),
            new MimeItem(".jam", "application/x-jam"),
            new MimeItem(".jar", "application/java-archive"),
            new MimeItem(".java", "text/plain"),
            new MimeItem(".jfif", "image/pipeg"),
            new MimeItem(".jnlp", "application/x-java-jnlp-file"),
            new MimeItem(".jpe", "image/jpeg"),
            new MimeItem(".jpeg", "image/jpeg"),
            new MimeItem(".jpg", "image/jpeg"),
            new MimeItem(".jpz", "image/jpeg"),
            new MimeItem(".js", "application/x-javascript"),
            new MimeItem(".jwc", "application/jwc"),
            new MimeItem(".kjx", "application/x-kjx"),
            new MimeItem(".lak", "x-lml/x-lak"),
            new MimeItem(".latex", "application/x-latex"),
            new MimeItem(".lcc", "application/fastman"),
            new MimeItem(".lcl", "application/x-digitalloca"),
            new MimeItem(".lcr", "application/x-digitalloca"),
            new MimeItem(".lgh", "application/lgh"),
            new MimeItem(".lha", "application/octet-stream"),
            new MimeItem(".lml", "x-lml/x-lml"),
            new MimeItem(".lmlpack", "x-lml/x-lmlpack"),
            new MimeItem(".log", "text/plain"),
            new MimeItem(".lsf", "video/x-la-asf"),
            new MimeItem(".lsx", "video/x-la-asf"),
            new MimeItem(".lzh", "application/octet-stream"),
            new MimeItem(".m13", "application/x-msmediaview"),
            new MimeItem(".m14", "application/x-msmediaview"),
            new MimeItem(".m15", "audio/x-mod"),
            new MimeItem(".m3u", "audio/x-mpegurl"),
            new MimeItem(".m3url", "audio/x-mpegurl"),
            new MimeItem(".m4a", "audio/mp4a-latm"),
            new MimeItem(".m4b", "audio/mp4a-latm"),
            new MimeItem(".m4p", "audio/mp4a-latm"),
            new MimeItem(".m4u", "video/vnd.mpegurl"),
            new MimeItem(".m4v", "video/x-m4v"),
            new MimeItem(".ma1", "audio/ma1"),
            new MimeItem(".ma2", "audio/ma2"),
            new MimeItem(".ma3", "audio/ma3"),
            new MimeItem(".ma5", "audio/ma5"),
            new MimeItem(".man", "application/x-troff-man"),
            new MimeItem(".map", "magnus-internal/imagemap"),
            new MimeItem(".mbd", "application/mbedlet"),
            new MimeItem(".mct", "application/x-mascot"),
            new MimeItem(".mdb", "application/x-msaccess"),
            new MimeItem(".mdz", "audio/x-mod"),
            new MimeItem(".me", "application/x-troff-me"),
            new MimeItem(".mel", "text/x-vmel"),
            new MimeItem(".mht", "message/rfc822"),
            new MimeItem(".mhtml", "message/rfc822"),
            new MimeItem(".mi", "application/x-mif"),
            new MimeItem(".mid", "audio/mid"),
            new MimeItem(".midi", "audio/midi"),
            new MimeItem(".mif", "application/x-mif"),
            new MimeItem(".mil", "image/x-cals"),
            new MimeItem(".mio", "audio/x-mio"),
            new MimeItem(".mmf", "application/x-skt-lbs"),
            new MimeItem(".mng", "video/x-mng"),
            new MimeItem(".mny", "application/x-msmoney"),
            new MimeItem(".moc", "application/x-mocha"),
            new MimeItem(".mocha", "application/x-mocha"),
            new MimeItem(".mod", "audio/x-mod"),
            new MimeItem(".mof", "application/x-yumekara"),
            new MimeItem(".mol", "chemical/x-mdl-molfile"),
            new MimeItem(".mop", "chemical/x-mopac-input"),
            new MimeItem(".mov", "video/quicktime"),
            new MimeItem(".movie", "video/x-sgi-movie"),
            new MimeItem(".mp2", "video/mpeg"),
            new MimeItem(".mp3", "audio/mpeg"),
            new MimeItem(".mp4", "video/mp4"),
            new MimeItem(".mpa", "video/mpeg"),
            new MimeItem(".mpc", "application/vnd.mpohun.certificate"),
            new MimeItem(".mpe", "video/mpeg"),
            new MimeItem(".mpeg", "video/mpeg"),
            new MimeItem(".mpg", "video/mpeg"),
            new MimeItem(".mpg4", "video/mp4"),
            new MimeItem(".mpga", "audio/mpeg"),
            new MimeItem(".mpn", "application/vnd.mophun.application"),
            new MimeItem(".mpp", "application/vnd.ms-project"),
            new MimeItem(".mps", "application/x-mapserver"),
            new MimeItem(".mpv2", "video/mpeg"),
            new MimeItem(".mrl", "text/x-mrml"),
            new MimeItem(".mrm", "application/x-mrm"),
            new MimeItem(".ms", "application/x-troff-ms"),
            new MimeItem(".msg", "application/vnd.ms-outlook"),
            new MimeItem(".mts", "application/metastream"),
            new MimeItem(".mtx", "application/metastream"),
            new MimeItem(".mtz", "application/metastream"),
            new MimeItem(".mvb", "application/x-msmediaview"),
            new MimeItem(".mzv", "application/metastream"),
            new MimeItem(".nar", "application/zip"),
            new MimeItem(".nbmp", "image/nbmp"),
            new MimeItem(".nc", "application/x-netcdf"),
            new MimeItem(".ndb", "x-lml/x-ndb"),
            new MimeItem(".ndwn", "application/ndwn"),
            new MimeItem(".nif", "application/x-nif"),
            new MimeItem(".nmz", "application/x-scream"),
            new MimeItem(".nokia-op-logo", "image/vnd.nok-oplogo-color"),
            new MimeItem(".npx", "application/x-netfpx"),
            new MimeItem(".nsnd", "audio/nsnd"),
            new MimeItem(".nva", "application/x-neva1"),
            new MimeItem(".nws", "message/rfc822"),
            new MimeItem(".oda", "application/oda"),
            new MimeItem(".ogg", "audio/ogg"),
            new MimeItem(".oom", "application/x-AtlasMate-Plugin"),
            new MimeItem(".p10", "application/pkcs10"),
            new MimeItem(".p12", "application/x-pkcs12"),
            new MimeItem(".p7b", "application/x-pkcs7-certificates"),
            new MimeItem(".p7c", "application/x-pkcs7-mime"),
            new MimeItem(".p7m", "application/x-pkcs7-mime"),
            new MimeItem(".p7r", "application/x-pkcs7-certreqresp"),
            new MimeItem(".p7s", "application/x-pkcs7-signature"),
            new MimeItem(".pac", "audio/x-pac"),
            new MimeItem(".pae", "audio/x-epac"),
            new MimeItem(".pan", "application/x-pan"),
            new MimeItem(".pbm", "image/x-portable-bitmap"),
            new MimeItem(".pcx", "image/x-pcx"),
            new MimeItem(".pda", "image/x-pda"),
            new MimeItem(".pdb", "chemical/x-pdb"),
            new MimeItem(".pdf", "application/pdf"),
            new MimeItem(".pfr", "application/font-tdpfr"),
            new MimeItem(".pfx", "application/x-pkcs12"),
            new MimeItem(".pgm", "image/x-portable-graymap"),
            new MimeItem(".pict", "image/x-pict"),
            new MimeItem(".pko", "application/ynd.ms-pkipko"),
            new MimeItem(".pm", "application/x-perl"),
            new MimeItem(".pma", "application/x-perfmon"),
            new MimeItem(".pmc", "application/x-perfmon"),
            new MimeItem(".pmd", "application/x-pmd"),
            new MimeItem(".pml", "application/x-perfmon"),
            new MimeItem(".pmr", "application/x-perfmon"),
            new MimeItem(".pmw", "application/x-perfmon"),
            new MimeItem(".png", "image/png"),
            new MimeItem(".pnm", "image/x-portable-anymap"),
            new MimeItem(".pnz", "image/png"),
            new MimeItem(".pot,", "application/vnd.ms-powerpoint"),
            new MimeItem(".ppm", "image/x-portable-pixmap"),
            new MimeItem(".pps", "application/vnd.ms-powerpoint"),
            new MimeItem(".ppt", "application/vnd.ms-powerpoint"),
            new MimeItem(".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"),
            new MimeItem(".pqf", "application/x-cprplayer"),
            new MimeItem(".pqi", "application/cprplayer"),
            new MimeItem(".prc", "application/x-prc"),
            new MimeItem(".prf", "application/pics-rules"),
            new MimeItem(".prop", "text/plain"),
            new MimeItem(".proxy", "application/x-ns-proxy-autoconfig"),
            new MimeItem(".ps", "application/postscript"),
            new MimeItem(".ptlk", "application/listenup"),
            new MimeItem(".pub", "application/x-mspublisher"),
            new MimeItem(".pvx", "video/x-pv-pvx"),
            new MimeItem(".qcp", "audio/vnd.qcelp"),
            new MimeItem(".qt", "video/quicktime"),
            new MimeItem(".qti", "image/x-quicktime"),
            new MimeItem(".qtif", "image/x-quicktime"),
            new MimeItem(".r3t", "text/vnd.rn-realtext3d"),
            new MimeItem(".ra", "audio/x-pn-realaudio"),
            new MimeItem(".ram", "audio/x-pn-realaudio"),
            new MimeItem(".rar", "application/octet-stream"),
            new MimeItem(".ras", "image/x-cmu-raster"),
            new MimeItem(".rc", "text/plain"),
            new MimeItem(".rdf", "application/rdf+xml"),
            new MimeItem(".rf", "image/vnd.rn-realflash"),
            new MimeItem(".rgb", "image/x-rgb"),
            new MimeItem(".rlf", "application/x-richlink"),
            new MimeItem(".rm", "audio/x-pn-realaudio"),
            new MimeItem(".rmf", "audio/x-rmf"),
            new MimeItem(".rmi", "audio/mid"),
            new MimeItem(".rmm", "audio/x-pn-realaudio"),
            new MimeItem(".rmvb", "audio/x-pn-realaudio"),
            new MimeItem(".rnx", "application/vnd.rn-realplayer"),
            new MimeItem(".roff", "application/x-troff"),
            new MimeItem(".rp", "image/vnd.rn-realpix"),
            new MimeItem(".rpm", "audio/x-pn-realaudio-plugin"),
            new MimeItem(".rt", "text/vnd.rn-realtext"),
            new MimeItem(".rte", "x-lml/x-gps"),
            new MimeItem(".rtf", "application/rtf"),
            new MimeItem(".rtg", "application/metastream"),
            new MimeItem(".rtx", "text/richtext"),
            new MimeItem(".rv", "video/vnd.rn-realvideo"),
            new MimeItem(".rwc", "application/x-rogerwilco"),
            new MimeItem(".s3m", "audio/x-mod"),
            new MimeItem(".s3z", "audio/x-mod"),
            new MimeItem(".sca", "application/x-supercard"),
            new MimeItem(".scd", "application/x-msschedule"),
            new MimeItem(".sct", "text/scriptlet"),
            new MimeItem(".sdf", "application/e-score"),
            new MimeItem(".sea", "application/x-stuffit"),
            new MimeItem(".setpay", "application/set-payment-initiation"),
            new MimeItem(".setreg", "application/set-registration-initiation"),
            new MimeItem(".sgm", "text/x-sgml"),
            new MimeItem(".sgml", "text/x-sgml"),
            new MimeItem(".sh", "application/x-sh"),
            new MimeItem(".shar", "application/x-shar"),
            new MimeItem(".shtml", "magnus-internal/parsed-html"),
            new MimeItem(".shw", "application/presentations"),
            new MimeItem(".si6", "image/si6"),
            new MimeItem(".si7", "image/vnd.stiwap.sis"),
            new MimeItem(".si9", "image/vnd.lgtwap.sis"),
            new MimeItem(".sis", "application/vnd.symbian.install"),
            new MimeItem(".sit", "application/x-stuffit"),
            new MimeItem(".skd", "application/x-Koan"),
            new MimeItem(".skm", "application/x-Koan"),
            new MimeItem(".skp", "application/x-Koan"),
            new MimeItem(".skt", "application/x-Koan"),
            new MimeItem(".slc", "application/x-salsa"),
            new MimeItem(".smd", "audio/x-smd"),
            new MimeItem(".smi", "application/smil"),
            new MimeItem(".smil", "application/smil"),
            new MimeItem(".smp", "application/studiom"),
            new MimeItem(".smz", "audio/x-smd"),
            new MimeItem(".snd", "audio/basic"),
            new MimeItem(".spc", "application/x-pkcs7-certificates"),
            new MimeItem(".spl", "application/futuresplash"),
            new MimeItem(".spr", "application/x-sprite"),
            new MimeItem(".sprite", "application/x-sprite"),
            new MimeItem(".sdp", "application/sdp"),
            new MimeItem(".spt", "application/x-spt"),
            new MimeItem(".src", "application/x-wais-source"),
            new MimeItem(".sst", "application/vnd.ms-pkicertstore"),
            new MimeItem(".stk", "application/hyperstudio"),
            new MimeItem(".stl", "application/vnd.ms-pkistl"),
            new MimeItem(".stm", "text/html"),
            new MimeItem(".svg", "image/svg+xml"),
            new MimeItem(".sv4cpio", "application/x-sv4cpio"),
            new MimeItem(".sv4crc", "application/x-sv4crc"),
            new MimeItem(".svf", "image/vnd"),
            new MimeItem(".svg", "image/svg+xml"),
            new MimeItem(".svh", "image/svh"),
            new MimeItem(".svr", "x-world/x-svr"),
            new MimeItem(".swf", "application/x-shockwave-flash"),
            new MimeItem(".swfl", "application/x-shockwave-flash"),
            new MimeItem(".t", "application/x-troff"),
            new MimeItem(".tad", "application/octet-stream"),
            new MimeItem(".talk", "text/x-speech"),
            new MimeItem(".tar", "application/x-tar"),
            new MimeItem(".taz", "application/x-tar"),
            new MimeItem(".tbp", "application/x-timbuktu"),
            new MimeItem(".tbt", "application/x-timbuktu"),
            new MimeItem(".tcl", "application/x-tcl"),
            new MimeItem(".tex", "application/x-tex"),
            new MimeItem(".texi", "application/x-texinfo"),
            new MimeItem(".texinfo", "application/x-texinfo"),
            new MimeItem(".tgz", "application/x-compressed"),
            new MimeItem(".thm", "application/vnd.eri.thm"),
            new MimeItem(".tif", "image/tiff"),
            new MimeItem(".tiff", "image/tiff"),
            new MimeItem(".tki", "application/x-tkined"),
            new MimeItem(".tkined", "application/x-tkined"),
            new MimeItem(".toc", "application/toc"),
            new MimeItem(".toy", "image/toy"),
            new MimeItem(".tr", "application/x-troff"),
            new MimeItem(".trk", "x-lml/x-gps"),
            new MimeItem(".trm", "application/x-msterminal"),
            new MimeItem(".tsi", "audio/tsplayer"),
            new MimeItem(".tsp", "application/dsptype"),
            new MimeItem(".tsv", "text/tab-separated-values"),
            new MimeItem(".ttf", "application/octet-stream"),
            new MimeItem(".ttz", "application/t-time"),
            new MimeItem(".txt", "text/plain"),
            new MimeItem(".uls", "text/iuls"),
            new MimeItem(".ult", "audio/x-mod"),
            new MimeItem(".ustar", "application/x-ustar"),
            new MimeItem(".uu", "application/x-uuencode"),
            new MimeItem(".uue", "application/x-uuencode"),
            new MimeItem(".vcd", "application/x-cdlink"),
            new MimeItem(".vcf", "text/x-vcard"),
            new MimeItem(".vdo", "video/vdo"),
            new MimeItem(".vib", "audio/vib"),
            new MimeItem(".viv", "video/vivo"),
            new MimeItem(".vivo", "video/vivo"),
            new MimeItem(".vmd", "application/vocaltec-media-desc"),
            new MimeItem(".vmf", "application/vocaltec-media-file"),
            new MimeItem(".vmi", "application/x-dreamcast-vms-info"),
            new MimeItem(".vms", "application/x-dreamcast-vms"),
            new MimeItem(".vox", "audio/voxware"),
            new MimeItem(".vqe", "audio/x-twinvq-plugin"),
            new MimeItem(".vqf", "audio/x-twinvq"),
            new MimeItem(".vql", "audio/x-twinvq"),
            new MimeItem(".vre", "x-world/x-vream"),
            new MimeItem(".vrml", "x-world/x-vrml"),
            new MimeItem(".vrt", "x-world/x-vrt"),
            new MimeItem(".vrw", "x-world/x-vream"),
            new MimeItem(".vts", "workbook/formulaone"),
            new MimeItem(".wav", "audio/x-wav"),
            new MimeItem(".wax", "audio/x-ms-wax"),
            new MimeItem(".wbmp", "image/vnd.wap.wbmp"),
            new MimeItem(".wcm", "application/vnd.ms-works"),
            new MimeItem(".wdb", "application/vnd.ms-works"),
            new MimeItem(".web", "application/vnd.xara"),
            new MimeItem(".wi", "image/wavelet"),
            new MimeItem(".wis", "application/x-InstallShield"),
            new MimeItem(".wks", "application/vnd.ms-works"),
            new MimeItem(".wm", "video/x-ms-wm"),
            new MimeItem(".wma", "audio/x-ms-wma"),
            new MimeItem(".wmd", "application/x-ms-wmd"),
            new MimeItem(".wmf", "application/x-msmetafile"),
            new MimeItem(".wml", "text/vnd.wap.wml"),
            new MimeItem(".wmlc", "application/vnd.wap.wmlc"),
            new MimeItem(".wmls", "text/vnd.wap.wmlscript"),
            new MimeItem(".wmlsc", "application/vnd.wap.wmlscriptc"),
            new MimeItem(".wmlscript", "text/vnd.wap.wmlscript"),
            new MimeItem(".wmv", "audio/x-ms-wmv"),
            new MimeItem(".wmx", "video/x-ms-wmx"),
            new MimeItem(".wmz", "application/x-ms-wmz"),
            new MimeItem(".wpng", "image/x-up-wpng"),
            new MimeItem(".wps", "application/vnd.ms-works"),
            new MimeItem(".wpt", "x-lml/x-gps"),
            new MimeItem(".wri", "application/x-mswrite"),
            new MimeItem(".wrl", "x-world/x-vrml"),
            new MimeItem(".wrz", "x-world/x-vrml"),
            new MimeItem(".ws", "text/vnd.wap.wmlscript"),
            new MimeItem(".wsc", "application/vnd.wap.wmlscriptc"),
            new MimeItem(".wv", "video/wavelet"),
            new MimeItem(".wvx", "video/x-ms-wvx"),
            new MimeItem(".wxl", "application/x-wxl"),
            new MimeItem(".x-gzip", "application/x-gzip"),
            new MimeItem(".xaf", "x-world/x-vrml"),
            new MimeItem(".xar", "application/vnd.xara"),
            new MimeItem(".xbm", "image/x-xbitmap"),
            new MimeItem(".xdm", "application/x-xdma"),
            new MimeItem(".xdma", "application/x-xdma"),
            new MimeItem(".xdw", "application/vnd.fujixerox.docuworks"),
            new MimeItem(".xht", "application/xhtml+xml"),
            new MimeItem(".xhtm", "application/xhtml+xml"),
            new MimeItem(".xhtml", "application/xhtml+xml"),
            new MimeItem(".xla", "application/vnd.ms-excel"),
            new MimeItem(".xlc", "application/vnd.ms-excel"),
            new MimeItem(".xll", "application/x-excel"),
            new MimeItem(".xlm", "application/vnd.ms-excel"),
            new MimeItem(".xls", "application/vnd.ms-excel"),
            new MimeItem(".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"),
            new MimeItem(".xlt", "application/vnd.ms-excel"),
            new MimeItem(".xlw", "application/vnd.ms-excel"),
            new MimeItem(".xm", "audio/x-mod"),
            new MimeItem(".xml","text/plain"),
            new MimeItem(".xml","application/xml"),  
            new MimeItem(".xmz", "audio/x-mod"),
            new MimeItem(".xof", "x-world/x-vrml"),
            new MimeItem(".xpi", "application/x-xpinstall"),
            new MimeItem(".xpm", "image/x-xpixmap"),
            new MimeItem(".xsit", "text/xml"),
            new MimeItem(".xsl", "text/xml"),
            new MimeItem(".xul", "text/xul"),
            new MimeItem(".xwd", "image/x-xwindowdump"),
            new MimeItem(".xyz", "chemical/x-pdb"),
            new MimeItem(".yz1", "application/x-yz1"),
            new MimeItem(".z", "application/x-compress"),  
            new MimeItem(".zac", "application/x-zaurus-zac"),
            new MimeItem(".zip", "application/zip"),
            new MimeItem(".json", "application/json")
        };

        public class MimeItem
        {
            public string Mime { get; set; }

            public string Extension { get; set; }

            public MimeItem(string extension, string mime)
            {
                Mime = mime;
                Extension = extension;
            }
        }
    }
}