name: publish to nuget

on:
  push:
    tags:
    - 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Publish Jx.Toolboox
      uses: tedd/publish-nuget-neo@v1.0.2
      with:
        PROJECT_FILE_PATH: Jx.Toolbox/Jx.Toolbox.csproj
        VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Jx.Toolbox.HtmlTools
      uses: tedd/publish-nuget-neo@v1.0.2
      with:
        PROJECT_FILE_PATH: Jx.Toolbox.HtmlTools/Jx.Toolbox.HtmlTools.csproj
        VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
    - name: Publish Jx.Toolbox.Mvc
      uses: tedd/publish-nuget-neo@v1.0.2
      with:
        PROJECT_FILE_PATH: Jx.Toolbox.HtmlTools/Jx.Toolbox.Mvc.csproj
        VERSION_REGEX: ^\s*<PackageVersion>(.*)<\/PackageVersion>\s*$
        NUGET_KEY: ${{secrets.NUGET_API_KEY}}
